---

type: docker
kind: pipeline
name: build-latest-container

steps:
    - name: build latest container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          tags: latest
    - name: build tag container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          auto_tag: true

trigger:
    event:
        - tag

---

type: docker
kind: pipeline
name: build-dev-container

steps:
    - name: build dev container
      image: plugins/docker
      settings:
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          repo: keyoxide/keyoxide
          tags: dev

trigger:
    branch:
        - dev
    event:
        - push
