<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/favicon.png">
        <title>Keyoxide</title>
        <link rel="stylesheet" href="/assets/styles.css">
    </head>
    <body>
        <div class="container container--profile">
            <div class="content">
                <span id="profileUid" style="display: none;"><?=$this->escape($uid)?></span>
                <span id="profileMode" style="display: none;"><?=$this->escape($mode)?></span>
                <div id="profileHeader">
                    <img id="profileAvatar" src="/assets/img/avatar_placeholder.png" alt="avatar" style="display: none">
                    <p id="profileName"></p>
                </div>
                <div id="profileData"><p>Loading keys &amp; verifying proofs&hellip;</p></div>
            </div>

            <footer>
                <p>Page generated by <a href="/">Keyoxide</a>.</p>
            </footer>
        </div>
    </body>
    <script src="/assets/openpgp.min.js"></script>
    <script src="/assets/spark-md5.min.js"></script>
    <script type="text/javascript" src="/assets/scripts.js" charset="utf-8"></script>
</html>
